[package]
name = "bevy_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_polyline = "0.7.0"
polyhedron = { path = "../polyhedron" }